version: 2

project_name: git-cx

builds:
  - main: .
    binary: git-cx
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version=v{{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

release:
  draft: false
  prerelease: auto
